### ISSUE TITLE
Not working on Node 4.x

### ISSUE THREAD

**Issue by Frijol** [tessel/t1-cli#189]
See https://forums.tessel.io/t/can-not-install-npm-tessel-1-on-os-x-10-11-1-and-node-v4-2-1/2099

**Comment by CarlQLange** [comment]
Also doesn't appear to work on node 5.0, some really odd output (don't have it to hand, sorry!)

**Comment by vsviridov** [comment]
Updating to the latest version of usb module seems to at least fix the CLI.

**Comment by mbrevda** [comment]
How did you update @vsviridov?

**Comment by vsviridov** [comment]
@mbrevda, i think I tweaked the package.json by hand and re-ran `npm install`.

**Comment by EvanSimpson** [comment]
Hey @mbrevda, @vsviridov the fix should now be in for tessel@0.3.24, thanks for chiming in on this one!
